apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: awsservices.earou.io
spec:
  group: earou.io
  version: v1
  names:
    kind: AWSService
    plural: awsservices
    singular: awsservice
  scope: Namespaced